---
- name: Initial Configuration - Stage 1
  hosts: all
  vars:
    ansible_user: root
  vars_files:
    - vars.yml
  tags: stage1

  tasks:
    - import_tasks: tasks/users.yml

- name: Initial Configuration - Stage 2
  hosts: all
  become: yes
  remote_user: '{{ ssh_user }}'
  tags: stage2
  vars_files:
    - vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - import_tasks: tasks/apt.yml

    - import_tasks: tasks/secure-ssh.yml

    - import_tasks: tasks/ufw.yml

    - name: Check if reboot required
      stat: path=/var/run/reboot-required get_md5=no
      register: reboot_required

    - name: Reboot machine if required
      reboot:
        reboot_timeout: 3600
      when: reboot_required.stat.exists == true

