---
- name: LAMP Stack
  hosts: all
  become: yes
  remote_user: '{{ ssh_user }}' 
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if required
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Get pre-requisites
      apt:
        name:
          - python-apt
          - python-pycurl
          - python-pip
          - git
          - curl
          - unzip
          - sendmail
        state: present

    - import_tasks: tasks/apache.yml
      tags: webserver

    - import_tasks: tasks/ufw.yml

    - import_tasks: tasks/php56-tasks.yml
      tags: php

    - import_tasks: tasks/mysql.yml
      tags: mysql
