---
- name: Deploy website
  hosts: all
  become: yes
  remote_user: '{{ ssh_user }}'
  vars_files:
    - vars.yml

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Create document root
      file:
        path: '{{ domain_root_path }}'
        state: directory
        mode: 0755

    - name: Copy index test page
      template:
        src: templates/index.html.j2
        dest: '{{ domain_root_path }}/index.html'

    - name: Copy phpinfo test page
      template:
        src: templates/info.php.j2
        dest: '{{ domain_root_path }}/info.php'

    - name: Configure vhost
      template:
        src: templates/apache2.vhost.conf.j2
        dest: '/etc/apache2/sites-available/{{ domain_name }}.conf'

    - name: Enable site
      shell: '/usr/sbin/a2ensite {{ domain_name }}.conf'
      notify: Reload apache
