---
- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Disable root SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart ssh

#- name: Configure ufw firewall
#  ufw:
#    rule: allow
#    port: '{{ item }}'
#  loop: '{{ ufw_allow_ports }}'


